export { syncHandlers } from './handlers/sync-handlers'
export { integrationHandlers } from './handlers/integration-handlers'
export { historyHandlers } from './handlers/history-handlers'
export { error502Handler, error400Handler, errorHandlers } from './handlers/error-handlers'
export { localHandlers } from './handlers/local-handlers'
export { mockSyncChanges } from './data/sync-changes'
export { mockIntegrations } from './data/integrations'
export { mockHistory } from './data/history'
export { localSnapshotStore, type LocalSnapshotRecord } from './data/local-snapshots'
export { localAuditLog } from './data/local-history'
// Note: browser.ts is NOT re-exported from index because it imports 'msw/browser'
// which is browser-only. Import browser.ts directly when needed.