/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationIntegrationIdRouteImport } from './routes/integration.$integrationId'
import { Route as IntegrationIntegrationIdIndexRouteImport } from './routes/integration.$integrationId.index'
import { Route as IntegrationIntegrationIdReviewRouteImport } from './routes/integration.$integrationId.review'
import { Route as IntegrationIntegrationIdHistoryRouteImport } from './routes/integration.$integrationId.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationIntegrationIdRoute =
  IntegrationIntegrationIdRouteImport.update({
    id: '/integration/$integrationId',
    path: '/integration/$integrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationIntegrationIdIndexRoute =
  IntegrationIntegrationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => IntegrationIntegrationIdRoute,
  } as any)
const IntegrationIntegrationIdReviewRoute =
  IntegrationIntegrationIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => IntegrationIntegrationIdRoute,
  } as any)
const IntegrationIntegrationIdHistoryRoute =
  IntegrationIntegrationIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => IntegrationIntegrationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integration/$integrationId': typeof IntegrationIntegrationIdRouteWithChildren
  '/integration/$integrationId/history': typeof IntegrationIntegrationIdHistoryRoute
  '/integration/$integrationId/review': typeof IntegrationIntegrationIdReviewRoute
  '/integration/$integrationId/': typeof IntegrationIntegrationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integration/$integrationId/history': typeof IntegrationIntegrationIdHistoryRoute
  '/integration/$integrationId/review': typeof IntegrationIntegrationIdReviewRoute
  '/integration/$integrationId': typeof IntegrationIntegrationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integration/$integrationId': typeof IntegrationIntegrationIdRouteWithChildren
  '/integration/$integrationId/history': typeof IntegrationIntegrationIdHistoryRoute
  '/integration/$integrationId/review': typeof IntegrationIntegrationIdReviewRoute
  '/integration/$integrationId/': typeof IntegrationIntegrationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integration/$integrationId'
    | '/integration/$integrationId/history'
    | '/integration/$integrationId/review'
    | '/integration/$integrationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integration/$integrationId/history'
    | '/integration/$integrationId/review'
    | '/integration/$integrationId'
  id:
    | '__root__'
    | '/'
    | '/integration/$integrationId'
    | '/integration/$integrationId/history'
    | '/integration/$integrationId/review'
    | '/integration/$integrationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrationIntegrationIdRoute: typeof IntegrationIntegrationIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/$integrationId': {
      id: '/integration/$integrationId'
      path: '/integration/$integrationId'
      fullPath: '/integration/$integrationId'
      preLoaderRoute: typeof IntegrationIntegrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration/$integrationId/': {
      id: '/integration/$integrationId/'
      path: '/'
      fullPath: '/integration/$integrationId/'
      preLoaderRoute: typeof IntegrationIntegrationIdIndexRouteImport
      parentRoute: typeof IntegrationIntegrationIdRoute
    }
    '/integration/$integrationId/review': {
      id: '/integration/$integrationId/review'
      path: '/review'
      fullPath: '/integration/$integrationId/review'
      preLoaderRoute: typeof IntegrationIntegrationIdReviewRouteImport
      parentRoute: typeof IntegrationIntegrationIdRoute
    }
    '/integration/$integrationId/history': {
      id: '/integration/$integrationId/history'
      path: '/history'
      fullPath: '/integration/$integrationId/history'
      preLoaderRoute: typeof IntegrationIntegrationIdHistoryRouteImport
      parentRoute: typeof IntegrationIntegrationIdRoute
    }
  }
}

interface IntegrationIntegrationIdRouteChildren {
  IntegrationIntegrationIdHistoryRoute: typeof IntegrationIntegrationIdHistoryRoute
  IntegrationIntegrationIdReviewRoute: typeof IntegrationIntegrationIdReviewRoute
  IntegrationIntegrationIdIndexRoute: typeof IntegrationIntegrationIdIndexRoute
}

const IntegrationIntegrationIdRouteChildren: IntegrationIntegrationIdRouteChildren =
  {
    IntegrationIntegrationIdHistoryRoute: IntegrationIntegrationIdHistoryRoute,
    IntegrationIntegrationIdReviewRoute: IntegrationIntegrationIdReviewRoute,
    IntegrationIntegrationIdIndexRoute: IntegrationIntegrationIdIndexRoute,
  }

const IntegrationIntegrationIdRouteWithChildren =
  IntegrationIntegrationIdRoute._addFileChildren(
    IntegrationIntegrationIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrationIntegrationIdRoute: IntegrationIntegrationIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
